/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginpagewithvendingoption;

import java.awt.event.KeyEvent;

/**
 *
 * @author Jeffrey Toquero
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        accname = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        toSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AccountPage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        updatePage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 0, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accname.setFont(new java.awt.Font("Swis721 Hv BT", 1, 48)); // NOI18N
        accname.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.add(accname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 430, 110));

        jLabel1.setFont(new java.awt.Font("Swis721 Blk BT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hello,");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, 130));

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        kGradientPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpagewithvendingoption/mov1.png"))); // NOI18N
        jScrollPane1.setViewportView(jLabel3);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 890, 320));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpagewithvendingoption/mov2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jScrollPane2.setViewportView(jLabel2);

        kGradientPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 890, 320));

        toSearch.setBackground(new java.awt.Color(0, 0, 0));
        toSearch.setForeground(new java.awt.Color(255, 255, 255));
        toSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toSearchActionPerformed(evt);
            }
        });
        toSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                toSearchKeyPressed(evt);
            }
        });
        kGradientPanel1.add(toSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 190, 50));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        AccountPage.setForeground(new java.awt.Color(255, 255, 255));
        AccountPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpagewithvendingoption/person-244 (2).png"))); // NOI18N
        AccountPage.setText("Account");
        AccountPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountPageMouseClicked(evt);
            }
        });
        kGradientPanel1.add(AccountPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 90, 40));

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Vending Features ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 40));

        updatePage.setBackground(new java.awt.Color(51, 0, 0));
        updatePage.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        updatePage.setForeground(new java.awt.Color(255, 255, 255));
        updatePage.setText("What's new?");
        updatePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePageActionPerformed(evt);
            }
        });
        kGradientPanel1.add(updatePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
       LoginPage login = new LoginPage();
   login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void toSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toSearchKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
          Search insearch = new Search();
      insearch.setVisible(true);  
      insearch.tosearch.setText(toSearch.getText());
    
 this.dispose();
       }      
    }//GEN-LAST:event_toSearchKeyPressed

    private void toSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      VendingMachine openVen = new VendingMachine();
      openVen.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AccountPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountPageMouseClicked
     Account accInfo = new Account();
     accInfo.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_AccountPageMouseClicked

    private void updatePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePageActionPerformed
     WhatsnewPage upd = new WhatsnewPage();
     upd.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_updatePageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountPage;
    public static javax.swing.JLabel accname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField toSearch;
    private javax.swing.JButton updatePage;
    // End of variables declaration//GEN-END:variables
}
