/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginpagewithvendingoption;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author Jeffrey Toquero
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        accName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bgpanel = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        accPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 0, 0));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accName.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        accName.setForeground(new java.awt.Color(255, 51, 51));
        accName.setActionCommand("<Not Set>");
        accName.setAutoscrolls(false);
        accName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        accName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                accNameFocusGained(evt);
            }
        });
        accName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(accName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 180, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Username");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 70, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 70, 20));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei Light", 2, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("''Watch movies for free''");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 140, 30));

        jLabel4.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ROOM");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 110, 60));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 130, 40));

        bgpanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpagewithvendingoption/user-headphone-300.png"))); // NOI18N
        bgpanel.setText("jLabel5");
        kGradientPanel1.add(bgpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 540));

        kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 530));

        jLabel6.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("WELCOME TO");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 210, 60));

        jLabel7.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("THE MOVIE");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 190, 60));

        accPass.setForeground(new java.awt.Color(255, 51, 51));
        accPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accPassActionPerformed(evt);
            }
        });
        accPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                accPassKeyPressed(evt);
            }
        });
        kGradientPanel1.add(accPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 400, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNameActionPerformed
           accName.getText();
           accName.setText(" "); 
    }//GEN-LAST:event_accNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String user = accName.getText();
       String pass = accPass.getText();
       
       if(user.isEmpty()||user.equals("Jeffrey") ||pass.isEmpty()|| pass.equals("1234")){
           Dashboard dash = new Dashboard();
           dash.setVisible(true);
            Dashboard.accname.setText(accName.getText());
           this.dispose();
       }
       else{
           JOptionPane.showMessageDialog(null,"Please check if what you entered is correct");
       }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
     if(evt.getKeyCode()==KeyEvent.VK_ENTER){
          Dashboard login = new Dashboard();
      login.setVisible(true);  
       Dashboard.accname.setText(accName.getText());
    
      this.dispose();
       }
      
    }//GEN-LAST:event_jButton1KeyPressed

    private void accNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accNameFocusGained
   if(accName.getText().equals("Enter Username")){
           accName.setText(" ");
     
}     
    }//GEN-LAST:event_accNameFocusGained

    private void accPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accPassActionPerformed

    private void accPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accPassKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
          Dashboard login = new Dashboard();
      login.setVisible(true);  
       Dashboard.accname.setText(accName.getText());
    
      this.dispose();
       }
    }//GEN-LAST:event_accPassKeyPressed

   
    public static void main(String args[]) {
   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accName;
    private javax.swing.JPasswordField accPass;
    private javax.swing.JLabel bgpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
