/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginpagewithvendingoption;

import javax.swing.JOptionPane;

/**
 *
 * @author Jeffrey Toquero
 */
public class VendingMachine extends javax.swing.JFrame {

    /**
     * Creates new form VendingMachine
     */   
    String Prod;
    String Quant;
    public VendingMachine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        b8 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        disPayment = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        disProd = new javax.swing.JTextField();
        disPrice = new javax.swing.JTextField();
        disQuant = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buying = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setkGradientFocus(250);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 204, 51));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b8.setBackground(new java.awt.Color(0, 255, 0));
        b8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        b8.setForeground(new java.awt.Color(255, 255, 255));
        b8.setText("SPARKLE");
        b8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b8MouseClicked(evt);
            }
        });
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 150, 70));

        b1.setBackground(new java.awt.Color(255, 51, 51));
        b1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("COKE");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 150, 70));

        b2.setBackground(new java.awt.Color(51, 255, 51));
        b2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("SPRITE");
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
        });
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 150, 70));

        b3.setBackground(new java.awt.Color(255, 102, 0));
        b3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("FANTA");
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3MouseClicked(evt);
            }
        });
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 150, 70));

        b4.setBackground(new java.awt.Color(0, 102, 255));
        b4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        b4.setText("PEPSI");
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b4MouseClicked(evt);
            }
        });
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 150, 70));

        b5.setBackground(new java.awt.Color(255, 153, 51));
        b5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        b5.setText("JAZZ");
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b5MouseClicked(evt);
            }
        });
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 150, 70));

        b6.setBackground(new java.awt.Color(102, 255, 0));
        b6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        b6.setText("7UP");
        b6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b6MouseClicked(evt);
            }
        });
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 150, 70));

        b7.setBackground(new java.awt.Color(0, 0, 153));
        b7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 255, 255));
        b7.setText("SUMMIT");
        b7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b7MouseClicked(evt);
            }
        });
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, 70));

        jLabel1.setFont(new java.awt.Font("Swis721 Blk BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRICE");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 290, 30));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 102, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("\t     Price List\nCOKE\t\tP12.00\n\nSPRITE\t\tP11.00\n\nFANTA\t\tP11.00\n\nPEPSI\t\tP12.00\n\nJAZZ\t\tP8.00\n\n7UP\t\tP9.00\n\nSUMMIT\t\tP10.00\n\nSPARKLE\t\tP8.00");
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane2.setViewportView(jScrollPane1);

        kGradientPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 280, 220));

        disPayment.setEditable(false);
        disPayment.setBackground(new java.awt.Color(102, 0, 0));
        disPayment.setFont(new java.awt.Font("CMG Sans Medium", 1, 36)); // NOI18N
        disPayment.setForeground(new java.awt.Color(255, 255, 255));
        disPayment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kGradientPanel1.add(disPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 290, 70));

        jLabel2.setFont(new java.awt.Font("Swis721 Blk BT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SELECT PRODUCT");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 270, 30));

        disProd.setEditable(false);
        disProd.setBackground(new java.awt.Color(0, 102, 102));
        disProd.setFont(new java.awt.Font("CMG Sans ExtraBold", 1, 18)); // NOI18N
        disProd.setForeground(new java.awt.Color(255, 255, 255));
        disProd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kGradientPanel1.add(disProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 290, 70));

        disPrice.setEditable(false);
        disPrice.setBackground(new java.awt.Color(0, 51, 51));
        disPrice.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        disPrice.setForeground(new java.awt.Color(255, 255, 255));
        disPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kGradientPanel1.add(disPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 290, 70));

        disQuant.setEditable(false);
        disQuant.setBackground(new java.awt.Color(0, 102, 102));
        disQuant.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        disQuant.setForeground(new java.awt.Color(255, 255, 255));
        disQuant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kGradientPanel1.add(disQuant, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 290, 70));

        jLabel3.setFont(new java.awt.Font("Swis721 Blk BT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SELECTED PRODUCT");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 290, 30));

        jLabel4.setFont(new java.awt.Font("Swis721 Blk BT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SELECTED QUANTITY");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 310, 30));

        jLabel6.setFont(new java.awt.Font("Swis721 Blk BT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TOTAL PAYMENT");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 290, 30));

        buying.setBackground(new java.awt.Color(255, 153, 0));
        buying.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buying.setText("BUY");
        buying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyingActionPerformed(evt);
            }
        });
        kGradientPanel1.add(buying, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 130, 40));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 130, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("CMG Sans ExtraBold", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
disProd.setText("COKE");
           disPrice.setText("12.00");
           Prod = "COKE";    
    }//GEN-LAST:event_b1ActionPerformed

    private void buyingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyingActionPerformed
 Quant = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");
double total;
            double quantity = Integer.parseInt(Quant);
            while(quantity>10||quantity<1)
            {
                JOptionPane.showMessageDialog(null,"Maximum is 10!");
                Quant = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");
                quantity = Integer.parseInt(Quant);      
            }
              disQuant.setText(Quant);
              if(null != Prod)
        switch (Prod) {
            case "COKE":
                total = quantity * 12;
                disPayment.setText("₱"+Double.toString(total)+"0");
                
                break;
                  case "SPRITE":
                total = quantity * 11;
                 disPayment.setText("₱"+Double.toString(total)+"0");
                
                break;
            case "FANTA":
                total = quantity * 11;
                 disPayment.setText("₱"+Double.toString(total)+"0");
                
                break;
            case "PEPSI":
                total = quantity * 12;
                 disPayment.setText("₱"+Double.toString(total)+"0");
                
                break;
            case "JAZZ":
                total = quantity * 8;
                 disPayment.setText("₱"+Double.toString(total)+"0");
                
                break;
            case "7UP":
                total = quantity * 9;
                 disPayment.setText("₱"+Double.toString(total)+"0");
                
                break;
            case "SUMMIT":
                total = quantity * 10;
                 disPayment.setText("₱"+Double.toString(total)+"0");
                
                break;
            case "SPARKLE":
                total = quantity * 8    ;
                 disPayment.setText("₱"+Double.toString(total)+"0");
                
                break;
            default:
                break;
     }                                      
    
    }//GEN-LAST:event_buyingActionPerformed

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b1MouseClicked

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b2MouseClicked

    private void b3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b3MouseClicked

    private void b4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b4MouseClicked

    private void b5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b5MouseClicked

    private void b6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b6MouseClicked

    private void b7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b7MouseClicked

    private void b8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_b8MouseClicked

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
    disProd.setText("FANTA");
         disPrice.setText("11.00");
          Prod = "FANTA";
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
      disProd.setText("PEPSI");
           disPrice.setText("12.00");
            Prod = "PEPSI";
    }//GEN-LAST:event_b4ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        disProd.setText("SPRITE");
      disPrice.setText("11.00");
      Prod = "SPRITE";
    }//GEN-LAST:event_b2ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        disProd.setText("JAZZ");
         disPrice.setText("8.00");
          Prod = "JAZZ";
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
       disProd.setText("7UP");
          disPrice.setText("9.00");
           Prod = "7UP";
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
      disProd.setText("SUMMIT");
           disPrice.setText("10.00");
            Prod = "SUMMIT";
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
       disProd.setText("SPARKLE");
         disPrice.setText("8.00");
          Prod = "SPARKLE";
    }//GEN-LAST:event_b8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        disPrice.setText("");
      disProd.setText("");
       disQuant.setText("");
          disPayment.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Dashboard fromvend = new Dashboard();
       fromvend.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendingMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton buying;
    private javax.swing.JTextField disPayment;
    private javax.swing.JTextField disPrice;
    private javax.swing.JTextField disProd;
    private javax.swing.JTextField disQuant;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
